image: ubuntu:latest

before_script:
    - apt-get update
    - apt-get install -y file wget curl python3-dev python3-venv build-essential
    - apt-get install -y libssl-dev libgtk-3-dev librsvg2-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev libjavascriptcoregtk-6.0-dev

    - python3 -m venv "${HOME}/.venv/"
    - source "${HOME}/.venv/bin/activate"
    - pip install pyinstaller

    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
    - bash -c "source '${HOME}/.nvm/nvm.sh' && nvm install --lts"

    - curl -fsSL https://sh.rustup.rs | bash -s -- -y

stages:
    - build

build_project:
    stage: build
    script:
        - source "${HOME}/.venv/bin/activate"
        - source "${HOME}/.nvm/nvm.sh"
        - source "${HOME}/.cargo/env"

        - npm --version
        - node --version
        - rustc --version
        - cargo --version
        - python3 --version
        - pyinstaller --version

        - ./gen/build.sh

        - npm install
        - npm run tauri-prod

        - scp src-tauri/binaries/nyx-gen-* "${DEPLOY_USER}"@"${DEPLOY_HOST}":/var/www/nyxlib.org/download/
        - scp src-tauri/target/release/bundle/appimage/nyx-assistant_*.AppImage "${DEPLOY_USER}"@"${DEPLOY_HOST}":/var/www/nyxlib.org/download/
