image: alpine

variables:
    NODE_VERSION: "0.40.0"

before_script:
    - apk update
    - apk add --no-cache curl rust cargo pkgconfig python3-dev py3-virtualenv gtk+3.0-dev libsoup3-dev webkit2gtk-dev

    - python3 -m venv "${HOME}/.venv/"
    - source "${HOME}/.venv/bin/activate"
    - pip install pyinstaller

    - curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v${NODE_VERSION}/install.sh" | bash
    - source "${HOME}/.nvm/nvm.sh"
    - nvm install 20

    - npm --version
    - node --version
    - rustc --version
    - python3 --version
    - pyinstaller --version

stages:
    - build

build_project:
    stage: build
    script:
        - source "${HOME}/.venv/bin/activate"
        - ./gen/build.sh

        - source "${HOME}/.nvm/nvm.sh"
        - npm install
        - npm run tauri-prod
    artifacts:
        paths:
            - tauri/binaries/nyx-gen-*
            - tauri/target/release/bundle/appimage/nyx-assistant_*.AppImage
        expire_in: 1 week
        when: always
    only:
        - main
