image: ubuntu:oracular

variables:
    NODE_VERSION: "0.40.0"

before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -

    - apt-get install -y make rustc cargo nodejs pkg-config python3-dev python3-venv
    - apt-get install -y libssl-dev libgtk-3-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev libjavascriptcoregtk-6.0-dev

    - python3 -m venv "${HOME}/.venv/"
    - source "${HOME}/.venv/bin/activate"
    - pip install pyinstaller

    - npm --version
    - node --version
    - rustc --version
    - cargo --version
    - python3 --version
    - pyinstaller --version

stages:
    - build

build_project:
    stage: build
    script:
        - source "${HOME}/.venv/bin/activate"
        - ./gen/build.sh

        - source "${HOME}/.nvm/nvm.sh"
        - npm install
        - npm run tauri-prod
    artifacts:
        paths:
            - tauri/binaries/nyx-gen-*
            - tauri/target/release/bundle/appimage/nyx-assistant_*.AppImage
        expire_in: 1 week
        when: always
    only:
        - main
