image: ubuntu:oracular

before_script:
    - apt-get update
    - apt-get install -y file wget curl
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -

    - apt-get install -y make rustc cargo nodejs pkg-config python3-dev python3-venv
    - apt-get install -y libssl-dev libgtk-3-dev librsvg2-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev libjavascriptcoregtk-6.0-dev

    - python3 -m venv "${HOME}/.venv/"
    - source "${HOME}/.venv/bin/activate"
    - pip install pyinstaller

    - npm --version
    - node --version
    - rustc --version
    - cargo --version
    - python3 --version
    - pyinstaller --version

stages:
    - build

build_project:
    stage: build
    script:
        - source "${HOME}/.venv/bin/activate"
        - ./gen/build.sh

        - npm install
        - npm run tauri-prod

        - mv src-tauri/binaries/nyx-gen-* ./nyx-gen
        - mv src-tauri/target/release/bundle/appimage/nyx-assistant_*.AppImage ./nyx-assistant.AppImage
    artifacts:
        paths:
            - ./nyx-gen
            - ./nyx-assistant.AppImage
        expire_in: 1 week
        when: always
    only:
        - main
