image: rust:latest

variables:
    NODE_VERSION: "0.40.0"

before_script:
    - apt-get update
    - apt-get install -y curl python3-venv
    - python3 -m venv ./venv/
    - source ./venv/bin/activate
    - pip install pyinstaller

    - curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v${NODE_VERSION}/install.sh" | bash
    - nvm install 20
    - export NVM_DIR="$HOME/.nvm"
    - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

    - npm --version
    - node --version
    - rustc --version
    - python3 --version
    - pyinstaller --version

stages:
    - build

build_project:
    stage: build
    script:
        - source ./venv/bin/activate
        - ./gen/build.sh
    artifacts:
        paths:
            - tauri/binaries/nyx-gen-*
        expire_in: 1 week
        when: always
    only:
        - main
